#ifndef _ELF_GRAPH_LIST_H_
#define _ELF_GRAPH_LIST_H_

typedef struct _ElfGraph ElfGraph;

#include <stdio.h>
#include <stdbool.h>

ElfGraph *elf_graph_new(int N, bool oriented);
void elf_graph_destroy(ElfGraph **graph_p);
int elf_graph_size(const ElfGraph *graph);
void elf_graph_addEdge(ElfGraph *graph, int src, int dest, int weight);
void elf_graph_removeEdge(ElfGraph *graph, int src, int dest);
void elf_graph_print(const ElfGraph *graph);
void elf_graph_printAdjacent(const ElfGraph *graph, int subjectVertex);
void elf_graph_readFromFileVE(ElfGraph *graph, FILE *fp, int lim);
void elf_graph_readFromFileVEW(ElfGraph *graph, FILE *fp, int lim);
void elf_graph_DFS_src(const ElfGraph *graph, int src, int **pred_p, int **time_p, int **finish_p);
int *elf_graph_BFS(const ElfGraph *graph, int src, int **dist_p);

/* DOCUMENTATION

ElfGraph
	- Graph implemented with an adjacency list.
	- Can be oriented or not.
	- Size must be specified on instantiation.
	- Double edges are not allowed.
 
ElfGraph *elf_graph_new(int N, bool oriented);
	- Returns a graph with N vertixes, indexed from 0 to N-1.
	- Graph is oriented if 'oriented' is true.

void elf_graph_destroy(ElfGraph **graph_p);
	- Deallocates all the memory used by 'graph', and sets its pointer to NULL.
	- 'graph' should be an ElfGraph* passed by reference (hence a double pointer).

int elf_graph_size(const ElfGraph *graph);
	- Returns the amount of vertixes in the graph.

void elf_graph_addEdge(ElfGraph *graph, int src, int dest, int weight);
	- Adds to the graph an edge from 'src' to 'dest'.
	- If the graph is not oriented, the inverse direction is also added.

void elf_graph_removeEdge(ElfGraph *graph, int src, int dest);
	- Removes, if exists, the edge going from 'src' to 'dest'.
	- If the graph is not oriented, the inverse is also removed.

void elf_graph_print(const ElfGraph *graph);
	- Prints the adjacency list of a graph

void elf_graph_printAdjacent(const ElfGraph *graph, int subjectVertex);
	- Prints indexes of vertices that are adjacent to 'subjectVertex'.
 
void elf_graph_readFromFileVE(ElfGraph *graph, FILE *fp, int lim);
	- Reads a sequence of 'lim' non-weighted edges from a file.
	- Reads until EOF if 'lim' is -1.
	- Will read any blank-character-separated sequence of integers,
	    following the order: source vertix - destiny vertix
	- VE stands for vertix and edge

void elf_graph_readFromFileVEW(ElfGraph *graph, FILE *fp, int lim);
	- Same as above, but also reads weights.
	- VEW stands for vertix, edge and weight

void elf_graph_DFS_src(const ElfGraph *graph, int src, int **pred_p, int **time_p, int **finish_p);
	- Performs a DFS in the graph, finding the time/path from all vertexes to 'src'.
	- Args:
	-	graph: pointer to the graph in which to execute the DFS.
	-	src: number of vertex to start the DFS from.
	-	pred_p: if not NULL, receives the vector of predecessors.
	-	time_p: if not NULL, receives the vector of time visited.
	-	finish_p: if not NULL, receives the vector of time finished.

int *elf_graph_BFS(const ElfGraph *graph, int src, int **dist_p);
	- Performs a BFS in the graph, finding the distance/path from all vertexes to 'src'.
	- Args:
	-   dist_p: If 'dist_p' is not NULL, store in it 
	-	        the vector of shortest distances to each vertex.
	-	        - dist[i] == -1, vertex could not be reached from 'src'.
	-	        - dist[i] != -1, shortest distance from 'src' to vertex i.
	- Returns:
	-   Vector of predecessors generated by the BFS.
	-	pred[i] == i means the vertix could not be reached,
	-	  with the exception of the source vertix, obviously
	-	pred[i] != i means vertix i could be visited and it's predecessor is pred[i]
	-	The predecessor vector must be freed by the client of the function.

*/

#endif
